name: blog_club
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/
  fonts:
    - family: avenger
      fonts:
        - asset: assets/fonts/avenir_regular.otf
        - asset: assets/fonts/avenir_bold.otf
          weight: 700
